import { ChromaClient, Collection } from "chromadb";

const CHROMA_HOST = "localhost";
const CHROMA_PORT = 8000;

let client: ChromaClient | null = null;

/**
 * Get a singleton ChromaDB client.
 *
 * SRIMATHY generates embeddings itself using Ollama
 * (nomic-embed-text, 768 dimensions).
 *
 * ChromaDB is used only as the vector store.
 */
function getClient(): ChromaClient {
    if (!client) {
        client = new ChromaClient({
            host: CHROMA_HOST,
            port: CHROMA_PORT,
            ssl: false,
        });
    }

    return client;
}

/**
 * Get or create the SRIMATHY knowledge collection.
 *
 * Important:
 * We explicitly disable Chroma's default embedding function.
 * Embeddings are generated by SRIMATHY/Ollama and supplied
 * directly to ChromaDB.
 */
export async function getKnowledgeCollection(): Promise<Collection> {
    const chroma = getClient();

    const collection = await chroma.getOrCreateCollection({
        name: "srimathy_knowledge",

        metadata: {
            description: "SRIMATHY educational knowledge base",
            embedding_dimension: 768,
        },

        embeddingFunction: null,
    });

    return collection;
}